"""first migrate

Revision ID: 30b0add14560
Revises: 
Create Date: 2025-05-08 22:19:12.282617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30b0add14560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserOperationLog')
    op.drop_table('ProblemRelation')
    with op.batch_alter_table('Problem', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题目id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('problem_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='题目名',
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='题目链接',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='题目创建时间',
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0-简单,1-中等,2-困难',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
        batch_op.alter_column('set_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题单id',
               existing_nullable=True)
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题目类型',
               existing_nullable=True)
        batch_op.drop_index('unique_link')
        batch_op.drop_table_comment(
        existing_comment='题目表'
    )

    with op.batch_alter_table('ProblemReview', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='1表示完成复习，0表示没有完成复习',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index('ProblemReview__create_time')
        batch_op.drop_index('ProblemReview__problem_id')
        batch_op.drop_index('ProblemReview__problem_set_id')
        batch_op.drop_index('ProblemReview__user_id')
        batch_op.create_index(batch_op.f('ix_ProblemReview_create_time'), ['create_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_ProblemReview_problem_id'), ['problem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ProblemReview_problem_set_id'), ['problem_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ProblemReview_user_id'), ['user_id'], unique=False)
        batch_op.drop_table_comment(
        existing_comment='每日复习题目表'
    )

    with op.batch_alter_table('ProblemSet', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题目id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('set_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='题目名',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='题目描述',
               existing_nullable=True)

    with op.batch_alter_table('ProblemType', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题型id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('type_level',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题型所处关系树中的深度',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='题型名',
               existing_nullable=True)
        batch_op.alter_column('parent_type_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='父类型id，如果是顶级，parent_id = 0',
               existing_nullable=True)
        batch_op.drop_index('prarent_type_id')
        batch_op.drop_index('type_name')
        batch_op.drop_table_comment(
        existing_comment='题目分类'
    )

    with op.batch_alter_table('SendEmailLog', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='操作的日期',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0-未发送，1-发送成功，2-发送失败',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='发送邮件日志'
    )

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('account',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='账号',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               comment=None,
               existing_comment='密码',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               type_=sa.String(length=100),
               comment=None,
               existing_comment='用户名',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=True)
        batch_op.drop_index('User_email_uindex')
        batch_op.drop_table_comment(
        existing_comment='用户表'
    )

    with op.batch_alter_table('UserProblem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0-未完成，1-完成',
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='最近一次完成时间',
               existing_nullable=True)
        batch_op.drop_table_comment(
        existing_comment='用户对应题目的完成情况'
    )

    with op.batch_alter_table('UserProblemLog', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
        batch_op.alter_column('problem_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题目id',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='0未完成，1完成',
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='打卡时间',
               existing_nullable=True)
        batch_op.drop_index('unique_user_problem')
        batch_op.drop_table_comment(
        existing_comment='记录用户对应的题目完成日志'
    )

    with op.batch_alter_table('UserProblemSetLog', schema=None) as batch_op:
        batch_op.alter_column('op_type',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='操作类型，1-创建题单，2-加入题单，3-退出题单，4-添加题目，5-删除题目，0-删除题单',
               existing_nullable=True)

    with op.batch_alter_table('UserSubscription', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户id',
               existing_nullable=True)
        batch_op.alter_column('set_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='题单id',
               existing_nullable=True)
        batch_op.alter_column('authority',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='用户是否可以修改题单，0不能修改，1可以修改',
               existing_nullable=True)
        batch_op.drop_index('unique_user_set')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserSubscription', schema=None) as batch_op:
        batch_op.create_index('unique_user_set', ['user_id', 'set_id'], unique=True)
        batch_op.alter_column('authority',
               existing_type=mysql.INTEGER(),
               comment='用户是否可以修改题单，0不能修改，1可以修改',
               existing_nullable=True)
        batch_op.alter_column('set_id',
               existing_type=mysql.INTEGER(),
               comment='题单id',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=True)

    with op.batch_alter_table('UserProblemSetLog', schema=None) as batch_op:
        batch_op.alter_column('op_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='操作类型，1-创建题单，2-加入题单，3-退出题单，4-添加题目，5-删除题目，0-删除题单',
               existing_nullable=True)

    with op.batch_alter_table('UserProblemLog', schema=None) as batch_op:
        batch_op.create_table_comment(
        '记录用户对应的题目完成日志',
        existing_comment=None
    )
        batch_op.create_index('unique_user_problem', ['user_id', 'problem_id'], unique=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='打卡时间',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0未完成，1完成',
               existing_nullable=True)
        batch_op.alter_column('problem_id',
               existing_type=mysql.INTEGER(),
               comment='题目id',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=True)

    with op.batch_alter_table('UserProblem', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户对应题目的完成情况',
        existing_comment=None
    )
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='最近一次完成时间',
               existing_nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0-未完成，1-完成',
               existing_nullable=True)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_table_comment(
        '用户表',
        existing_comment=None
    )
        batch_op.create_index('User_email_uindex', ['email'], unique=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               comment='用户名',
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               comment='密码',
               existing_nullable=True)
        batch_op.alter_column('account',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=255),
               comment='账号',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('SendEmailLog', schema=None) as batch_op:
        batch_op.create_table_comment(
        '发送邮件日志',
        existing_comment=None
    )
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='0-未发送，1-发送成功，2-发送失败',
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               comment='操作的日期',
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('ProblemType', schema=None) as batch_op:
        batch_op.create_table_comment(
        '题目分类',
        existing_comment=None
    )
        batch_op.create_index('type_name', ['type_name'], unique=True)
        batch_op.create_index('prarent_type_id', ['parent_type_id'], unique=False)
        batch_op.alter_column('parent_type_id',
               existing_type=mysql.INTEGER(),
               comment='父类型id，如果是顶级，parent_id = 0',
               existing_nullable=True)
        batch_op.alter_column('type_name',
               existing_type=mysql.VARCHAR(length=100),
               comment='题型名',
               existing_nullable=True)
        batch_op.alter_column('type_level',
               existing_type=mysql.INTEGER(),
               comment='题型所处关系树中的深度',
               existing_nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='题型id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ProblemSet', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               comment='题目描述',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=True)
        batch_op.alter_column('set_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='题目名',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='题目id',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ProblemReview', schema=None) as batch_op:
        batch_op.create_table_comment(
        '每日复习题目表',
        existing_comment=None
    )
        batch_op.drop_index(batch_op.f('ix_ProblemReview_user_id'))
        batch_op.drop_index(batch_op.f('ix_ProblemReview_problem_set_id'))
        batch_op.drop_index(batch_op.f('ix_ProblemReview_problem_id'))
        batch_op.drop_index(batch_op.f('ix_ProblemReview_create_time'))
        batch_op.create_index('ProblemReview__user_id', ['user_id'], unique=False)
        batch_op.create_index('ProblemReview__problem_set_id', ['problem_set_id'], unique=False)
        batch_op.create_index('ProblemReview__problem_id', ['problem_id'], unique=False)
        batch_op.create_index('ProblemReview__create_time', ['create_time'], unique=False)
        batch_op.alter_column('status',
               existing_type=mysql.INTEGER(),
               comment='1表示完成复习，0表示没有完成复习',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('Problem', schema=None) as batch_op:
        batch_op.create_table_comment(
        '题目表',
        existing_comment=None
    )
        batch_op.create_index('unique_link', ['user_id', 'set_id', 'link'], unique=True)
        batch_op.alter_column('type_id',
               existing_type=mysql.INTEGER(),
               comment='题目类型',
               existing_nullable=True)
        batch_op.alter_column('set_id',
               existing_type=mysql.INTEGER(),
               comment='题单id',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               comment='用户id',
               existing_nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=mysql.INTEGER(),
               comment='0-简单,1-中等,2-困难',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='题目创建时间',
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=255),
               comment='题目链接',
               existing_nullable=True)
        batch_op.alter_column('problem_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               comment='题目名',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               comment='题目id',
               existing_nullable=False,
               autoincrement=True)

    op.create_table('ProblemRelation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('target_problem_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relation', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='是否有关系，1表示有关系，0表示没有关系'),
    sa.PrimaryKeyConstraint('id'),
    comment='题目间关系，是否是同类型',
    mysql_comment='题目间关系，是否是同类型',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('UserOperationLog',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_permission', mysql.INTEGER(), autoincrement=False, nullable=True, comment='标记用户等级，0-普通用户，1-系统管理员'),
    sa.Column('ip', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('method', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='用户操作记录日志',
    mysql_comment='用户操作记录日志',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
